#PBS -N p_test(3)
#PBS -l nodes=2:ppn=8
#PBS -l walltime=15:00
#PBS -q coc-ice-multi
#PBS -o p_test(3).out
#PBS -e p_test(3).err

cd ~/CX4220-HighPerformance/HW2/pace-ice
module load gcc mvapich2/2.2

make

mpirun -np 9 ./nqueen 16 4 >> processorTest.txt
mpirun -np 10 ./nqueen 16 4 >> processorTest.txt
mpirun -np 11 ./nqueen 16 4 >> processorTest.txt
mpirun -np 12 ./nqueen 16 4 >> processorTest.txt
mpirun -np 13 ./nqueen 16 4 >> processorTest.txt
mpirun -np 14 ./nqueen 16 4 >> processorTest.txt
mpirun -np 15 ./nqueen 16 4 >> processorTest.txt
mpirun -np 16 ./nqueen 16 4 >> processorTest.txt
