#PBS -N np16_k_test(2)
#PBS -l nodes=2:ppn=8
#PBS -l walltime=30:00
#PBS -q coc-ice-multi
#PBS -o np16_k_test(2).out
#PBS -e np16_k_test(2).err

cd ~/CX4220-HighPerformance/HW2/pace-ice
module load gcc mvapich2/2.2

make

mpirun -np 16 ./nqueen 16 5 >> TIME_16proc.txt
mpirun -np 16 ./nqueen 16 6 >> TIME_16proc.txt
mpirun -np 16 ./nqueen 16 7 >> TIME_16proc.txt
mpirun -np 16 ./nqueen 16 8 >> TIME_16proc.txt
